### ISSUE TITLE
Doesn't work with Requests 0.9 or later

### ISSUE THREAD

**Issue by chris-morgan** [RallyTools/RallyRestToolkitForPython#1]
The latest version of `requests` that `pyral` will work with is 0.8.9; 0.9 turned on SSL verification by default (the only code change between 0.8.9 and 0.9 is the changing of `verify=None` in `Session.__init__`'s arguments to `verify=True`), and this has broken pyral:

```
H:\Private\pyral-0.8.9>python rallyfire.py
|rally1.rallydev.com| |wiley@acme.com| |G3ronim0!| |default| |default|
Traceback (most recent call last):
  File "H:\Private\pyral-0.8.9\rallyfire.py", line 56, in <module>
    main(sys.argv[1:])
  File "H:\Private\pyral-0.8.9\rallyfire.py", line 26, in main
    rally = Rally(server, user, password, workspace=workspace, project=project)
  File "H:\Private\pyral-0.8.9\pyral\restapi.py", line 165, in __init__
    self.contextHelper.check(self.server)
  File "H:\Private\pyral-0.8.9\pyral\context.py", line 182, in check
    raise RallyRESTAPIError(problem)
pyral.context.RallyRESTAPIError: 404 Target host: 'rally1.rallydev.com' doesn't support the Rally WSAPI
```

**Comment by chakpu** [comment]
I am having request timed out issue when trying to connect rally using pyral

I am using pyral 1.4.2 and request 2.19.1 and six 1.12.0 . I have installed certifi 2018.1.18

Code :
from pyral import Rally,rallyWorkset,RallyRESTAPIError
Server=‘rally1.rallydev.com’
api_key=‘my key’
workspace=‘ my workspace’
Project=‘my project’

rally=Rally(server, apikey =api_key,workspace=workspace, project=project,verify_ssl_cert=False)

response_userstory=rally.get(‘UserStory’,fetch=True, order=‘EndDate’)

for userstory in response_userstory:
    print(userstory.Name)

I have got proxy authentication failed once and after that I am continuously getting request timed out error

I am very new in programming.Can any one please guide me

**Comment by klehman-rally** [comment]
For Puja Chraborty, this is a closed issue.  You may want to open a new issue, however, your problem description sounds very much like slow network issues encountered by some other consumers of the pyral package.  The first actions would be to attempt to use curl to hit the Rally WSAPI endpoints to determine whether the timeouts that you are seeing are general and not specific to the use of pyral.  If there's no problem with using curl (or wget or similar programs) then you could attempt using python with requests and a proxy to see if the timeout problem persists.  At first glance I'm not convinced that this is indeed a pyral specific issue.
