### ISSUE TITLE
storyobject.Feature.FormattedID broken in pyral==1.2.2

### ISSUE THREAD

**Issue by haskalpa** [RallyTools/RallyRestToolkitForPython#101]
pyral==1.2.2
breaks:
```
Traceback (most recent call last):
  File "rally_common.py", line 608, in <module>
    get_complete_rally_item_diff_str()
  File "rally_common.py", line 533, in get_complete_rally_item_diff_str
    story_diff_str = complete_rally_item_diff(rally_conn, projects)
  File "rally_common.py", line 460, in complete_rally_item_diff
    exclude=exclude_list, is_story=is_story)
  File "rally_common.py", line 257, in get_item_dict
    print item.Feature.FormattedID
  File "/home/haskalpa/ss-work-new/packve/local/lib/python2.7/site-packages/pyral/entity.py", line 149, in __getattr__
    item = response.content[rallyEntityTypeName]
KeyError: 'PortfolioItem'
```
works fine in pyral==1.2.1

**Comment by klehman-rally** [comment]
In order to pin this down to a root cause, could you provide the snippet in your rally_common.py module that presumably does a query?  I'm particularly interested in how the fetch argument is constructed.  In general, the way to obtain sub-item item attributes where the sub-item is a ref to another entity is to explicitly name all the attributes in the fetch arg. Example fetch="ObjectID,Name,Feature,FormattedID"
.

**Comment by haskalpa** [comment]
@klehman-rally functional extract that would reproduce the issue hopefully should have everything that you are looking for. credentials for rally login and project names are read off a config which is not included.
[rally_common_tmp.py.txt](https://github.com/RallyTools/RallyRestToolkitForPython/files/635414/rally_common_tmp.py.txt)

**Comment by haskalpa** [comment]
traceback for this script
```
$ python rally_common_tmp.py 
Traceback (most recent call last):
  File "rally_common_tmp.py", line 98, in <module>
    storyies_dict = get_item_dict(stories)
  File "rally_common_tmp.py", line 81, in get_item_dict
    item_details['Feature'] = "{}:{}".format(item.Feature.FormattedID, item.Feature.Name)
  File "/home/haskalpa/ss-work-new/packve/local/lib/python2.7/site-packages/pyral/entity.py", line 149, in __getattr__
    item = response.content[rallyEntityTypeName]
KeyError: 'PortfolioItem'
```
and the issue is actually with calling 
```
item.Feature.FormattedID
```

**Comment by klehman-rally** [comment]
Thank you for the file. I was able to reproduce the behavior you encountered.

**Comment by klehman-rally** [comment]
I'm not going to categorize this as a defect.  The current behavior reflects the idiosyncrasy of the Agile Central WSAPI.  The desired effect can be achieved using the documented approach using the fetch=x argument with x being a comma separated list of attribute names.
