### ISSUE TITLE
Url for the 'six' library is incorrect.

### ISSUE THREAD

**Issue by trash-80** [RallyTools/RallyRestToolkitForPython#104]
On the README.rst:

The actual URL is: https://bitbucket.org/gutworth/six

Instead of: https://bitbucket/gutworth/six

Missing the ".org"

**Comment by klehman-rally** [comment]
Incorporating your correction in v1.2.4 which should be available within the next 10 days (from 2017-03-18).  Thanks for noticing this doc defect and creating an issue here!
