### ISSUE TITLE
RallyRestResponse.__repr__() raises KeyError if the query returned no results

### ISSUE THREAD

**Issue by pgacv2** [RallyTools/RallyRestToolkitForPython#106]
If a query returned no results, this method tries to create a string with `self.content['Results']`. It should be `self.content['QueryResult']['Results']`.

See pyral/rallyresp.py:

            if self.errors:
                blurb = self.errors[0]
            elif self.warnings:
                blurb = self.warnings[0]
            else:
                blurb = "%sResult TotalResultCount: %d  Results: %s" % \
                         (self.request_type, self.resultCount, self.content['Results'])
            return "%s %s" % (self.status_code, blurb)

**Comment by klehman-rally** [comment]
Processed the PR. code will be delivered in v1.2.4. Thanks!
