### ISSUE TITLE
Return Date fields as datetime instances, not strings

### ISSUE THREAD

**Issue by pgacv2** [RallyTools/RallyRestToolkitForPython#108]
It would be very convenient to have LastUpdateDate, AcceptedDate, etc. returned as timezone-aware datetime instances. That's what they really are, anyway. Other attributes such as Defect.Project or Defect.Release are already returned as the appropriate entity type, so returning datetimes here would improve consistency in the API. It would also provide the user immediate access to useful datetime methods instead of having to parse the string.

EntityHydrator._setAppropriateAttrValueForType() before:

        if type(attrValue) != dict:
            setattr(instance, attrName, attrValue)
            return

After:

        if type(attrValue) != dict:
            if attrName.endswith('Date') and attrValue:
                # Python doesn't recognize 'Z' as a valid timezone offset, so replace it with '+0000'.
                attrValue = datetime.datetime.strptime(attrValue[:-1] + '+0000', '%Y-%m-%dT%H:%M:%S.%f%z')
            setattr(instance, attrName, attrValue)
            return

**Comment by klehman-rally** [comment]
Passing on this request.  It's not clear that it is universally desirable to have datetime instances.  I'd agree that it is useful for some and that the expedient workaround is to define a convenience function that takes a RallyEntity instance and applies the logic you've illustrated as you pull them out of the RallyResponse.
