### ISSUE TITLE
Cannot get all attachments if several attachments have the same name

### ISSUE THREAD

**Issue by jfthuong** [RallyTools/RallyRestToolkitForPython#110]
Hi there,

I was trying to retrieve some attachments from my test cases in Rally and some of them got several attachments with the same name. As the current function `getAttachments` is looping though attachments by names, this did not work. Moreover an error occured while trying to do it.

The current code:

    def getAttachments(self, artifact):
        """
            For the given Artifact, return a list of Attachment records.
            Each Attachment record will look like a Rally WSAPI Attachment with
            the additional Content attribute that will contain the decoded AttachmentContent.
        """
        attachment_names = self.getAttachmentNames(artifact)
        attachments = [self.getAttachment(artifact, attachment_name) for attachment_name in attachment_names]
        attachments = [att for att in attachments if att is not None]
        return attachments

I ended up writing my own function (that returns a different result though to fit the code where it is used) inspired by `getAttachements` and `getAttachment`

	import base64
	from pyral.rallyresp import RallyRESTResponse
        def getAttachments(self):
		'''
		  Get a list of  all the attachments for the test case 
	          (dictionary with 3 keys: 'Name', 'oid', and 'Content')
		'''
		listAttachments = list()
		tcAttachments = self.entity.Attachments
		#List
		for att in tcAttachments:
			if not att._hydrated:
				getattr(att, 'Description')  # forces the hydration to occur
				
			context, augments = self.rally.contextHelper.identifyContext()
			resp = self.rally._getResourceByOID(context, 'AttachmentContent', att.Content.oid, project=None)
			if resp.status_code not in [200, 201, 202]:
				return None

			response = RallyRESTResponse(self.rally.session, context, "AttachmentContent.x", resp, "full", 1)
			if response.errors or response.resultCount != 1:
				return None
			att_content = response.next()
			att.Content = base64.decodestring(att_content.Content)  # maybe further txfm to Unicode ?
		
			listAttachments.append({k:getattr(att,k) for k in ['Name','oid','Content']})
		return listAttachments

**Comment by nikkisaumya** [comment]
@jfthuong(jean) @pgacv2 , do we have any work around for this issue ?

**Comment by jfthuong** [comment]
@nikkisaumya  My solution (provided in my post) used to work at that time. I don't know if it still does: you can try by yourself.

**Comment by klehman-rally** [comment]
Naming multiple attachments with the same value seems dysfunctional to me, but perhaps I don't understand your scenario well enough.  As you've addressed the problem for your use, I'm going to close this issue.  I'd be happy to re-open it for consideration if you want to provide your scenario/use-case along with code and test(s) that address this.

**Comment by jfthuong** [comment]
@klehman-rally 

It is indeed not recommended to have several attachments with the same name.

However, it used to be allowed by Rally: you can add add attachments in Rally and if they had the same name of an existing attachment, you would not get an error neither would the attachment be renamed something like "screenshot (1).jpg". Therefore, it was a case we could definitely encounter.

I cannot check if that is still the case as we stopped using Rally.

You can leave the issue closed if you wish and re-open it if someone else meets the same issue later on.
