### ISSUE TITLE
Using API Key prevents creation of tasks

### ISSUE THREAD

**Issue by marshallsmithatni** [RallyTools/RallyRestToolkitForPython#112]
I tried to write some code to automatically create tasks on some standard process management stories we create for each feature.  I wasn't able to, and kept getting:

> Response for request: task/create?key=None&workspace=workspace/xxxxxxxxxx&project=project/yyyyyyyyyyy either was not JSON content or was an invalidly formed/incomplete JSON structure

It looks like restapi.py intentionally prevents apikeys from creating rally objects:

```
def obtainSecurityToken(self):
        if self.apikey:
            return None
```

The Rally web interface provides an option for allowing full access for apikeys.  Is there any plan to allow apikeys to create objects through pyral?

**Comment by klehman-rally** [comment]
The capability to use an API Key value for an account to exercise the 4 major REST operations (query, create, update, delete) has been present for a few years in pyral.  
Was your API Key created as 'ALM WSAPI Read-only'?
If so, that would explain why you are unable to create a task using pyral and your API Key.
Create a new key and check the 'Full Access' option and use that.  (I just can't remember whether it is possible to change a read-only key into a full access key...).

**Comment by marshallsmithatni** [comment]
I had already changed the apikey to full access and it didn't have any effect.  I'll try creating a new one with that access and see if that changes anything.  I did run across a discussion somewhere indicating that SSO organizations weren't fully supported yet.  Is there a chance that has something to do with this?

**Comment by klehman-rally** [comment]
In an SSO enabled environment the use of API Key is the only way to utilize the AC REST API.
I'd recommended initially taking pyral/requests out of the equation and use something like Advanced REST Client in Chrome or just curl to see if you see the same behavior of not allowing creation of artifact(s).  First, here's an example of using curl to query for something using a (fake) API Key:curl --header "zsessionid:_1234ABCD...XYZ987" -H "Content-Type: application/json" https://rally1.rallydev.com/slm/webservice/v2.0/hierarchicalrequirement?query="(FormattedID = S111999)"&workspace=workspace/654321
