### ISSUE TITLE
Context is setting global default timeout on socket library

### ISSUE THREAD

**Issue by lmtierney** [RallyTools/RallyRestToolkitForPython#122]
https://github.com/RallyTools/RallyRestToolkitForPython/blob/master/pyral/context.py#L140

This can cause issues when a request within the same script takes over 5 seconds.

**Comment by klehman-rally** [comment]
In your environment, does a socket timeout happen frequently when attempting to obtain a pyral Rally instance?  For the most part, the AgileCentral SaaS infrastructure will not have a problem responding within the INITIAL_REQUEST_TIME_LIMIT (currently set at 5 seconds).  The more common circumstance will be that other network factors such as proxies, router settings, etc. will sometimes either not be set up correctly or under some sort of load wholly independent of AgileCentral.  I'm reluctant to expose setting of the INITIAL_REQUEST_TIME_LIMIT as there is a workaround of catching the exception in your application's driver code and retrying the "connection".  Of course, you are always free to make a local modification and set the INITIAL_REQUEST_TIME_LIMIT to a value that works in your particular environment.
