### ISSUE TITLE
rally.getAllUsers not fetching all user object attributes

### ISSUE THREAD

**Issue by anushreeapk** [RallyTools/RallyRestToolkitForPython#123]
Hi,

I am trying to fetch all attributes of the 'User' object for all users of a workspace, using an admin id for that workspace. 
Since,`user_response = rally.get('User',fetch=True,start = 1)` - returns information only of the current user. I got to know this was to be part of a future pyral update from [https://github.com/RallyTools/RallyRestToolkitForPython/issues/28](url)

I started using rally.getAllUsers instead. But saw that,
- The response returned does not contain all the attributes of the 'User' object as mentioned in [https://rally1.rallydev.com/slm/doc/webservice/](url) 
- I cannot apply a query to the get request (like we have a query param in rally.get) 

Both the user and users endpoint urls are working as expected in the web interface response.

**Comment by klehman-rally** [comment]
Here are the attributes available for a User entity returned from a call to the getAllUsers method: UserName, DisplayName, FirstName, MiddleName, LastName, ShortDisplayName,    
OnpremLdapUsername, CreationDate, EmailAddress, LastPasswordUpdateDate, Disabled,    
Subscription, SubscriptionAdmin, Role, UserPermissions, TeamMemberships,   
UserProfile, TimeZone  (a UserProfile attribute).

What attributes not in this list were you hoping to retrieve?  While the above list is not the whole set, it does seem to include the most used User attributes.

There are no plans to provide a query parameter to the getAllUsers convenience method.  Perhaps a local list comprehension for selection/filtering would meet your needs?

**Comment by rhgdas** [comment]
Here is my solution to this:

import pyral
from pyral import Rally
class GetUser:
    def __init__(self):
        self.ds_instance = os.getenv('DS_INSTANCE')
        self.ral_obj = Rally(server=os.getenv('RALLY_SERVER'), apikey=os.getenv('RALLY_APIKEY'),
                             workspace=os.getenv('RALLY_WORKSPACE'), project=self.project)
        self.START_INDEX = 1
        self.MAX_PAGESIZE = 2000
        self.MAX_ITEMS = 1000000
        self.SERVICE_REQUEST_TIMEOUT = 120
        self.HTTP_REQUEST_SUCCESS_CODE = 200
        self.PAGE_NOT_FOUND_CODE = 404

    def get_user_details(self):
        contextHelper = self.ral_obj.contextHelper
        session = self.ral_obj.session
        session.headers = pyral.config.RALLY_REST_HEADERS
        service_url = "%s://%s/%s" % (
            pyral.config.PROTOCOL, os.getenv("RALLY_SERVER"), pyral.config.WEB_SERVICE % pyral.config.WS_API_VERSION)
        saved_workspace_name, saved_workspace_ref = contextHelper.getWorkspace()
        workspace = saved_workspace_name
        self.ral_obj.setWorkspace(os.getenv('RALLY_WORKSPACE'))

        context, augments = contextHelper.identifyContext(workspace=workspace)
        workspace_ref = contextHelper.currentWorkspaceRef()

        user_attrs = ["UserName", "DisplayName",
                      "FirstName", "LastName", "MiddleName",
                      "ShortDisplayName", "OnpremLdapUsername",
                      "CreationDate", "EmailAddress",
                      "LastPasswordUpdateDate", "Disabled",
                      "Subscription", "SubscriptionAdmin",
                      "Role", "UserPermissions", "TeamMemberships",
                      "UserProfile",
                      "TimeZone",  # a UserProfile attribute
                      # and other UserProfile attributes
                      ]

        user_inclusion = "((Disabled = true) OR (Disabled = false))"
        users_resource = 'users?fetch=%s&query=%s&pagesize=%s&start=1&workspace=%s' % \
                         (",".join(user_attrs), user_inclusion , self.MAX_PAGESIZE, workspace_ref)
        full_resource_url = '%s/%s' % (service_url, users_resource)
        response = self.ral_obj.session.get(full_resource_url, timeout=self.SERVICE_REQUEST_TIMEOUT)
        if response.status_code != self.HTTP_REQUEST_SUCCESS_CODE:
            return []
        response = pyral.RallyRESTResponse(session, context, users_resource, response, "full", 0)
        if not response.errors:
            users = [user for user in response]
        return users

This method actually uses all components from pyral except the query builder, where we have issues when you have more than 4 pages. Increase the self.MAX_PAGESIZE in class initiation section and your issue will be resolved.
