### ISSUE TITLE
Defect in addCollectionItems prevents usage

### ISSUE THREAD

**Issue by DeezDB** [RallyTools/RallyRestToolkitForPython#128]
https://github.com/RallyTools/RallyRestToolkitForPython/blob/fc780ada9c5829dc39e315852aa9333bc4436c14/pyral/restapi.py#L1209

The line above has a typo in it, it currently is 

        outliers = [item for item in item_types if item._type != item_type]
  
It was presumably intended to be

        outliers = [item for item in item_types if item != item_type]

Thanks!

 - D

**Comment by klehman-rally** [comment]
This externally supplied remediation was included in the v1.4.1 release.  Thanks for the catch?
