### ISSUE TITLE
Add support for webhooks

### ISSUE THREAD

**Issue by jdewinne** [RallyTools/RallyRestToolkitForPython#130]
It would be nice if the python lib also supports the webhook api
https://rally1.rallydev.com/apps/pigeon/docs/webhooks

**Comment by klehman-rally** [comment]
I'll consider this for end of Q1 hackathon activities.  no promises...
Could you pass along what your predominant use of this would look like?  Scope, what part of CRUD you'd be using most, which would you classify as most useful, etc.

**Comment by jdewinne** [comment]
I would suggest starting with creating a webhook. Before implementing it should also be checked if this feature will be continued by Agile Central, as it is still in beta.

**Comment by klehman-rally** [comment]
Was not able to get to this at quarter end hackathon.  Have subsequently learned that there are significant issues precluding a near-term transition to GA status for the webhooks feature. I'm disappointed but hopeful that internal efforts may be revived to adequately resource the effort and design/implementation mods to ensure scalability will happen in the Q3 timeframe.  I'm going to close this issue.  Feel free to request a re-open for this issue or open a new similar issue if having webhooks CRUD support in pyral is a high priority for you
