### ISSUE TITLE
addCollectionItems - TypeError: 'Tag' object is not iterable

### ISSUE THREAD

**Issue by ssah-blr** [RallyTools/RallyRestToolkitForPython#137]
While trying to add a tag to a defect using addCollectionItems, getting following error -

print (defect.Name)
print (tag.details())
adds = rally.addCollectionItems(defect, tag)
print(adds)
--------------------
defect and tag are objects of defect and tag.
--------------------
Error in Python 3.5

    main(sys.argv[1])
    adds = rally.addCollectionItems(defect, tag)
  File "C:\Python35\lib\site-packages\pyral\restapi.py", line 1207, in addCollectionItems
    item_types = [item._type for item in items]
TypeError: 'Tag' object is not iterable

---------
Error in Python 2.7 

Traceback (most recent call last):
    main(sys.argv[1])
    adds = rally.addCollectionItems(defect, tag)
  File "C:\Python27\lib\site-packages\pyral\restapi.py", line 1207, in addCollectionItems
    item_types = [item._type for item in items]
TypeError: 'Tag' object is not iterable
--------

**Comment by klehman-rally** [comment]
per the documentation for the addCollectionItems method...
    
        Given a target_item and a homogenous list of items whose type appears as a One to Many relationship
        in the target item, add the collection_items to the corresponding attribute in the target_item.
        
Your way forward is to do this:
  tags = [tag]
  adds = rally.addCollectionItems(defect, tags)
