### ISSUE TITLE
Issues in tests of API

### ISSUE THREAD

**Issue by jfthuong** [RallyTools/RallyRestToolkitForPython#139]
9 Tests files seem have problems related to values missing in `rally_targets.py`; in particular:

* the value `API_KEY` has been commented in commit 108b39e7bacdbbf7e5af65229d11e80b11e93552, 
* `YETI` user and `LARGE_PROJECT` have been removed in de2d1dc9c063fac49d560d3f2f1793ede714fff2.

> 
> ________________ ERROR collecting test/test_allowed_values.py _________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_allowed_values.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_allowed_values.py:15: in <module>
>     from rally_targets import API_KEY
> E   ImportError: cannot import name API_KEY
> ___________________ ERROR collecting test/test_big_query.py ___________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_big_query.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_big_query.py:19: in <module>
>     from rally_targets import AGICEN, AGICEN_USER, AGICEN_PSWD, API_KEY
> E   ImportError: cannot import name API_KEY
> _____________________ ERROR collecting test/test_conn.py ______________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_conn.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_conn.py:18: in <module>
>     from rally_targets import PROD, API_KEY
> E   ImportError: cannot import name API_KEY
> __________________ ERROR collecting test/test_folder_misc.py __________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_folder_misc.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_folder_misc.py:5: in <module>
>     from internal_rally_targets import APIKEY, WORKSPACE, PROJECT
> E   ImportError: No module named internal_rally_targets
> ________________ ERROR collecting test/test_project_pathing.py ________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_project_pathing.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_project_pathing.py:13: in <module>
>     from rally_targets import YETI_USER, YETI_PSWD
> E   ImportError: cannot import name YETI_USER
> ______________ ERROR collecting test/test_pull_request_copied.py ______________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_pull_request_copied.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_pull_request_copied.py:16: in <module>
>     from internal_rally_targets import APIKEY
> E   ImportError: No module named internal_rally_targets
> ____________________ ERROR collecting test/test_search.py _____________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_search.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_search.py:14: in <module>
>     from internal_rally_targets import APIKEY, WORKSPACE, PROJECT
> E   ImportError: No module named internal_rally_targets
> ____________________ ERROR collecting test/test_update.py _____________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_update.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_update.py:21: in <module>
>     from rally_targets import         YETI_USER,   YETI_PSWD
> E   ImportError: cannot import name YETI_USER
> ________________ ERROR collecting test/test_wksprj_setting.py _________________
> ImportError while importing test module 'c:\SVN\WorkRoot\RallyRestToolkitForPython\test\test_wksprj_setting.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> test_wksprj_setting.py:16: in <module>
>     from rally_targets import API_KEY
> E   ImportError: cannot import name API_KEY
> !!!!!!!!!!!!!!!!!!! Interrupted: 9 errors during collection !!!!!!!!!!!!!!!!!!!

**Comment by klehman-rally** [comment]
Hi Jeff, this is the first time that issue has come up from external to Rally/CA.  So I salute you as being external adventurer #1 with respect to pyral automated testing.  The brief response is that you'll need to set up a rally_targets.py file in the test subdirectory and populate it with creds, workspaces and projects that you have access to.  Next, you'd probably have to alter some tests to reflect data in your system.  You could easily change all the YETI_* items to your favorite name, cola, car manufacturer, galaxy, etc.  and you'd have to set up an API_KEY or two for your username.
The longer term would be to modify the testing to allow for dynamic data creation to eliminate the need for static data.  However, as this is _still_ a hackathon project (that is nearly 7 years old...) that is officially unsupported, I don't see it as high on probability list any time soon.

**Comment by jfthuong** [comment]
I have used `pyral` quite a lot over the last 2 years and I have been Validation Leader for almost 10 years so it is normal that I had a look at pyral tests at some point.

My initial intention was to check why issues in attachments were not detected OR whether the modification I was proposing would work (or maybe something because April was kind of another life already).

So, what you mean is that `rally_targets.py` is a kind of template that should be customized before running the tests?

The idea of dynamically creating data would be nice. If I manage to get some time, I will see if I can create something on my branch. Maybe with a `ini` file to configure before running the test (with API keys, Workspace name, etc...)
