### ISSUE TITLE
Add support for indexing for RallyRESTResponse objects

### ISSUE THREAD

**Issue by aaronlelevier** [RallyTools/RallyRestToolkitForPython#142]
### Summary

Would it be possible to add support for indexing for `RallyRESTResponse` objects?

Here is the code and current error message when trying to index:

### Code

```python
from pyral import Rally

rally = Rally(...)
response = rally.get('UserStory')
response[0]
```

### Error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-a73c4cb8a3c5> in <module>()
----> 1 response[0]

TypeError: 'RallyRESTResponse' object does not support indexing
```

**Comment by klehman-rally** [comment]
The result from a rally.get(...) operation is a RallyRESTResponse instance.  That instance has an iterator characteristic so you can do either of:
first_item = rally.get('Story').next()
or
response = rally.get('Story')
all_stories = [item for item in response]
story_one = all_stories[0]
story_last = all_stories[-1]

I have no current plans to support indexing, but I'd be interested in learning about how you'd use it if it existed.  If the iterator protocol  doesn't meet your needs, I'm open to a clear explanation of how indexing is the right solution for your problem domain.
