### ISSUE TITLE
Unable to specify path to certfile in Rally() kwarg verify_ssl_cert

### ISSUE THREAD

**Issue by Meussdorffer** [RallyTools/RallyRestToolkitForPython#143]
I'm in a situation where I need to specify path to certfile for ssl auth. My workaround was to edit restapi.py to locate my .cer file when setting up the session. I've seen this as a common functionality in other apis / packages.

**Comment by klehman-rally** [comment]
I'd consider this with the contribution of code and test(s).  Otherwise, the value has a small potential audience and I won't be incorporating this feature.
