### ISSUE TITLE
No apparent way to fetch data about closed projects

### ISSUE THREAD

**Issue by pgacv2** [RallyTools/RallyRestToolkitForPython#144]
`getProjects()` uses `getAccessibleProjects()`, which does not return closed projects. `getProject()` returns `None` if you give it the name of a closed project. [This SO question](https://stackoverflow.com/questions/50686756/how-to-get-rally-stories-in-closed-projects-using-pyral) is also about getting user stories from closed projects.

Getting information about closed projects is probably not a common need, but it would be handy when you want to run metrics on old projects.

**Comment by pgacv2** [comment]
Using `project.Children`, however, does return a project's closed child projects.

**Comment by tep-pl** [comment]
👍

**Comment by klehman-rally** [comment]
My recollection is that up to some point the Rally WSAPI did support getting information on a closed Project (but only for subscription admin role and maybe? the workspace admin role).  However, there was a performance issue and the capability to retrieve information about Projects in the 'Closed' State was excluded.  You can confirm this by nav'ing in your browser to https://rally1.rallydev.com/slm/doc/webservice/ , select the 'Project' item on the left column and then paste in the Query String text box the string "(State = Closed)" and then click the 'Query' button associated with the Project item.
