### ISSUE TITLE
error in connecting Rally from python via pyral using API key 

### ISSUE THREAD

**Issue by sujoychakraborty93** [RallyTools/RallyRestToolkitForPython#146]
Hi, 
My organization uses SSO authentication. I am getting error while trying to connect rally using api key from python via pyral. Not sure what i am doing wrong. Any help is appreciated! 
I am using below code in the sample.py file (only change is I am entering the API key value, workspace name and project name) - 

import sys
from pyral import Rally, rallyWorkset
options = [arg for arg in sys.argv[1:] if arg.startswith('--')]
args    = [arg for arg in sys.argv[1:] if arg not in options]
server, user, password, apikey, workspace, project = rallyWorkset(options)
print(server)
rally = Rally('rally1.rallydev.com', apikey='<my api key>', workspace='<workspace name>', project='<project name>')
rally.enableLogging('mypyral.log')
workspaces = rally.getWorkspaces()
for wksp in workspaces:
	print("%s %s" % (wksp.oid, wksp.Name))
	projects = rally.getProjects(workspace=wksp.Name)
	for proj in projects:
		print("%12.12s  %s" % (proj.oid, proj.Name))

ERROR I am getting - 
rally1.rallydev.com
Traceback (most recent call last):
  File "sample.py", line 10, in <module>
    rally = Rally('rally1.rallydev.com', apikey='<my api key>', workspace='<workspace name>', project='<project name>')
  File "C:\...\Python\Python36\lib\site-packages\pyral\restapi.py", line 259, in __init__
    self.contextHelper.check(self.server, wksp, proj, self.isolated_workspace)
  File "C:\...\Python\Python36\lib\site-packages\pyral\context.py", line 171, in check
    user_response = self._getUserInfo()
  File "C:\...\Python\Python36\lib\site-packages\pyral\context.py", line 276, in _getUserInfo
    raise RallyRESTAPIError(problem)
pyral.context.RallyRESTAPIError: Target Rally host: 'rally1.rallydev.com' non-existent or unreachable

**Comment by tsal** [comment]
@sujoychakraborty93 - this looks like a DNS issue:

```
Target Rally host: 'rally1.rallydev.com' non-existent or unreachable
```

Can you `nslookup rally1.rallydev.com` or `ping rally1.rallydev.com` from the machine running the code?

**Comment by tsal** [comment]
I did more digging into this; it's directly related to the disabling of TLS1.0 - if your python version is built against an older openssl, or is using an older requests lib, it's probably the path to fixing this.

The other option (not appropriate for me) is using python3.

**Comment by tsal** [comment]
Also, if you're on a Mac, I strongly recommend using virtualenv and the following (this got me past the error): 

```
pip install requests[security]
```

**Comment by sujoychakraborty93** [comment]
Thanks @tsal for the details. Actually it was occurring because of http proxy. Below are the steps that worked for me - 
- go to pyral location
 -edit config.py file to include your rally log in credentials for fields USER_NAME and PASSWORD
- open command prompt in admin mode and run command set HTTPS_PROXY==http://user:password@proxy.domain.com:port
- for user id/psw, use your SSO credentials and not Rally credentials (if they are different).
- Then run the file sample.py and it worked
