### ISSUE TITLE
post() failure 'No classFor item for EngrFeature'

### ISSUE THREAD

**Issue by NCarteazy** [RallyTools/RallyRestToolkitForPython#151]
I'm encountering an issue while running the following:
`post_res = rally.post('EngrFeature', dict(c_UpdatedField = "xxxxx", ObjectID = test_oid), workspace=workspace,
                    project="XXXXXXX")`

The error given is:
`No classFor item for |EngrFeature|
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyral/hydrate.py", line 91, in _basicInstance
instance = classFor[str(itemType)](oid, name, resource_url, self.context)
KeyError: 'EngrFeature'`

The same error is also received when using 'PortfolioItem/EngrFeature'. This is a different error than what you receive upon giving an invalid EntityName.

I know that this EntityName is at least partially supported, because running 'get' returns properly:
`    
res = rally.get('EngrFeature', fetch=True, workspace=workspace,
                    project="XXXXXXXX", projectScopeDown=True)
`

**Comment by NCarteazy** [comment]
After further examination, it appears that the 'post' successfully performs its operation. It looks like only the hydration of the returned object is failing.

**Comment by klehman-rally** [comment]
What version of pyral are you running?  The lastest release version is 1.4.2.
We tried against one of our test subscriptions with a custom PortfolioItem type and did not observe the behavior you encounted.  Attaching the code we used so you can compare it against yours.
We ran it with pytest, but if you don't use that you can just run the code after modifying to call the two functions of interest.

def test_get_standard_pi(): 
    fields = "Name,PlannedStartDate" 
    criterion = None 
    response = rally.get('Feature', fetch=fields, query=criterion, pagesize=200, limit=2000) 
    for pi in response: 
        print("Name: %s, PlannedStartDate: %s" % (pi.Name, pi.PlannedStartDate)) 

    instance = rally.get('Feature', fetch=fields, query=criterion, pagesize=200, limit=2000, instance=True) 
    assert instance.Name == 'test standard pi' 

def test_get_custom_pi(): 
    fields = "Name,PlannedStartDate" 
    criterion = None 
    response = rally.get('EngrFeature', fetch=fields, query=criterion, pagesize=200, limit=2000) 
    for pi in response: 
        print("Name: %s, PlannedStartDate: %s" % (pi.Name, pi.PlannedStartDate)) 
    instance = rally.get('EngrFeature', fetch=fields, query=criterion, pagesize=200, limit=2000, instance=True) 
    assert instance.Name == 'test custom pi'

**Comment by NCarteazy** [comment]
I am also running pyral 1.4.2.

The issue wasn't occurring when running rally.get for Feature or EngrFeature, only on rally.post with EngrFeature. Running rally.post on Feature worked as expected, allowing the returned Rally object to be accessed.

**Comment by klehman-rally** [comment]
This has been fixed in the 1.5.0 release.
