### ISSUE TITLE
Could not get Release...

### ISSUE THREAD

**Issue by KapsGit** [RallyTools/RallyRestToolkitForPython#154]
I am trying to get the "Release" information for "User stories" but having problems. 

Following is the code:
f.write("{}, {}, {}, {} \n".format(str(UserStory.FormattedID),
                                               str(UserStory.Name),
                                               str(UserStory.AcceptedDate),
                                               str(UserStory.Release)))

Output prints the address like below rather than the value.
US2167, ABC, 2015-04-13T19:02:49.328Z, <pyral.entity.Iteration object at 0x0370A170> 
US2168, DDD, 2013-07-24T20:05:27.484Z, <pyral.entity.Iteration object at 0x0370AF70> 
US2196, CCC, 2015-04-13T20:54:24.237Z, <pyral.entity.Iteration object at 0x0370AF10> 

Can someone shed some light ?

**Comment by klehman-rally** [comment]
Amend your 4th parameter to the format function to be:  UserStory.Release.Name.
UserStory.Release is a ref value.  The toolkit provides the convenience operation where you can use dot notation to "traverse" the ref link automatically to access that ref target's attributes.
