### ISSUE TITLE
pyral.rallyresp.RallyResponseError: Response for request: testcaseresult/create?key=None | Apikey is None when required

### ISSUE THREAD

**Issue by Maytrovato** [RallyTools/RallyRestToolkitForPython#156]
If exists the apikey a None is returned and the URL for t he response looks like this  `testcaseresult/create?key=None`

pyral\restapi.py:340

What's the poing of this function? 
```
    def obtainSecurityToken(self):
        if self.apikey:
            return None
```

**Comment by klehman-rally** [comment]
If the request is not going to be using an API Key, then a security token will have to be obtained and used in a subsequent WSAPI request (There is more to the obtainSecurityToken method than what you've included in your comment).
If you are going to be using an API Key then yes the query string will include a key=None clause but on the Rally side that will be ignored as the mechanism will recognize that an API Key value was supplied in the header and use that (if it is a valid API Key).  I'm going to close this issue but if you've run into problems in running code that can be traced back to this, let me know and I'll be happy to re-open this issue.
