### ISSUE TITLE
Keyerror while hydrating custom PortfolioItem after a post() or put()

### ISSUE THREAD

**Issue by Sssnek1** [RallyTools/RallyRestToolkitForPython#158]
Hi, I'm having an issue with version 1.4.2 of pyral.
When I attempt to do a post/update with a custom PortfolioItem object pyral throws a keyerror exception.

The code I'm running is:
`rally.update('PortfolioItem/Vision', visInfo, workspace=DESTWORKSPACE, project=DESTPROJECT)` 
with Vision being the custom PortfolioItem.

The item updates correctly, but the error seems to be occurring after updating when the post/put tries to grab and return an instance of the updated item. It's worth noting that a get() of the object type works perfectly fine.

From what I can tell, it seems like the itemType name is getting truncated at some point from "PortfolioItem/Vision" to just "Vision" which causes it to break when it goes and tries to check the classFor dictionary, since it's expecting "PortfolioItem/Vision" as the key. See the image below for  more details on what's happening. The code is in hydrate.py at line 91.

![pyral issue](https://user-images.githubusercontent.com/57105595/67697615-d5cdc400-f976-11e9-8df8-398fb31c3c62.PNG)

Help would be much appreciated!

**Comment by klehman-rally** [comment]
This has been fixed in the 1.5.0 release.
