### ISSUE TITLE
How to call the service with an URL

### ISSUE THREAD

**Issue by KapsGit** [RallyTools/RallyRestToolkitForPython#159]
I am trying to get parent details of Component Feature (Portfolio item) but not sure how to do that.     I am able to get User story, it's Component feature and the ref link that points to it's parent(Marketable Feature) but not sure how to pass that to rally.get method.

![image](https://user-images.githubusercontent.com/11971506/72763192-2b95bf00-3ba8-11ea-99c5-f8102727fa33.png)

I want to pass the value in the _ref element(in the attachment) to get the details of it's parent. Or Is there any other way to get the parent details ?
Thanks for your time...

**Comment by klehman-rally** [comment]
A simple potential answer is that you could include the Parent field in the fetch list for this query.
The more complex aspect about this is the nature of your custom PI type hierarchy and how it was created.  The hierarchy of PI types is one in which you can change "levels" only by changing the names of the PI types, they are not drag-and-drop reorderable.

**Comment by KapsGit** [comment]
I don't have list of fields in the fetch...I pull everything and then pick only required attributes. Are you saying like Parent.Name ?

**Comment by klehman-rally** [comment]
There's a defect in 1.4.2 regarding custom PortfolioItem sub-types.  The 1.5.0 release will correct that defect.  The following information will be relevant for your specific issue subsequent to the 1.5.0 release.
The Toolkit is not set up to take refs in the supplied methods in the toolkit. It does support a dot notation that takes care of the refs and follow-up WSAPI calls to chase a ref and return a suitable pyral instance with which you can access sub-levels.
An example of that would be that you have the pyral instance of a ComponentFeature and you can get to it's Parent attributes via a syntax like cf.Parent.Name, cf.Parent.MarketSegment, cf.Parent.<SpecificAttributeName>  where cf is the pyral ComponentFeature instance. 
Another option is that once you have an instance of your ComponentFeature in hand from a Rally.get (again call it cf for example purposes),
get the Parent's FormattedID via  mf_fid = cf.Parent.FormattedID.  Then do an operation to obtain an instance of the target MarketableFeature, ie,
 rally.get('PortfolioItem/MarketableFeature', fetch=True, query='FormattedID = {0}'.fomat(mf_id))
 With the result of that you have access to all of the attributes of your ComponentFeature's parent.
