### ISSUE TITLE
How to retrieve user-facing/UI URL for a Defect (for example) ?

### ISSUE THREAD

**Issue by pallyndr** [RallyTools/RallyRestToolkitForPython#161]
Trying to retrieve Webui URL for a defect (as an example).

Seems end of URL is oid, but where can i find part after the # in the URL ?

https://rally1.rallydev.com/#/**26964342459ud**/detail/defect/326939995704

Thanks

**Comment by klehman-rally** [comment]
The portion you are referring to is workspace oid and scoping operators.  Every artifact (story (aka hierarchicalrequirement), task, defect, portfolio item, etc) lives in a specific workspace, which has an id.  The scoping operators are 'u' and 'd' (and sometimes not present at all).  The u and d are for scoping up and down from the point in the project hierarchy in the workspace. Now, strictly speaking if what you are after is just the individual item to be displayed, you don't have to use the scoping indicator at all.  Hope this addresses your intent, if not, post some more  clarifying info about what you are after.

**Comment by pallyndr** [comment]
Thanks Kip,

That explains the 'u' and 'd' thing.
But how can I get/retrieve the number (26964342459) from the API ?

I would like to have that returned by the API, as a "webui" parameter, as I can find in other APIs.

Thanks,

**Comment by klehman-rally** [comment]
The workspace ObjectID (oid) can be obtained using the getWorkspace/getWorkspaces methods for the the Rally instance in pyral/restapi.py.  Once you have that you can scope the calls to the 'get' method with that workspace (workspace=workspaces/<oid>). Then to get what you've called a WebUI URL, you'd construct it as seen in your initial inquiry.  There are no current plans to provide WebUI Urls from within pyral.
