### ISSUE TITLE
Get users for a Project

### ISSUE THREAD

**Issue by saurabh-9995** [RallyTools/RallyRestToolkitForPython#163]
Hey team,
We currently have the getAllUsers() method for getting users in a workspace. However, I am looking to get the names of all the users for a Project. Is there any method that i can use to achieve that?

Please reply asap. Thanks.

**Comment by klehman-rally** [comment]
There is no single method in the pyral module that will return the names of all the users for a given Project.  There is a potential indirect means, but it is relatively expensive, particularly if your Subscription is one in which there are many Users (roughly more than 1000).  You'd first have to get all the User items and then for each one resolve the UserPermissions collection to determine if they have any ProjectPermission to the target Project.  If you are in a Subscription in which a User is associated with relatively small subset number of Workspaces and Projects then the approach is both expensive and relatively wasteful (most ProjectPermission items associated with a typical User will not involve the target Project).  Sorry, I don't have a better answer.
