### ISSUE TITLE
Workspace name includes a space

### ISSUE THREAD

**Issue by johnhaprian** [RallyTools/RallyRestToolkitForPython#164]
Hi - I am a python noob so please bear with me...

My Rally workspace name contains two words separated by a space (e.g. "Company Workspace"). 

I am attempting to configure the "Common Setup Code" example from the README. Unfortunately I cannot figure out how to assign the workspace variable. I have tried:

```
workspace="Company Workspace"

workspace=`Company Workspace`

workspace = Company Workspace

workspace = Company\Workspace

workspace=`Company\Workspace`
```

All result in `SyntaxError: invalid syntax`. Any suggestions would be greatly appreciated. Thanks!

**Comment by dwij2812** [comment]
Hi @johnhaprian 

I tried the same with v1.4.2 and it works fine with a space when i specify
workspace="ABC XYZ 123"

**Comment by klehman-rally** [comment]
Unable to reproduce this in the environments I have available to me.
