### ISSUE TITLE
'RallyRESTResponse' object has no attribute 'ref'

### ISSUE THREAD

**Issue by saurabhbhagwat** [RallyTools/RallyRestToolkitForPython#168]
I am trying to fetch a user story using the FormattedID as follows:
fetchUserStory = rally.get('UserStory',query='FormattedID = %s'%userStoryID, instance=True)

I can see the user story in CA rally. But for some reason I am not able to retrieve it. I want to get the scheduled state of the user story. 

Please help me out asap.  @klehman-rally

**Comment by klehman-rally** [comment]
try double quoting the userStoryID value, eg.,
fetchUserStory = rally.get('UserStory',query='FormattedID = "%s"' % userStoryID, instance=True)

**Comment by saurabhbhagwat** [comment]
Got it sorted. The default project was wrongly pointing to some other project, thats why getting that error. Thanks for the help :) I'll close this one then.
