### ISSUE TITLE
Error trying to add a feature to collection (milestone)

### ISSUE THREAD

**Issue by reddevil311** [RallyTools/RallyRestToolkitForPython#169]
I am tying to add a feature to a collection - a milestone and I get below error. The code works just fine when I add a UserStory but throws an error when I add the feature. Any idea what could be the issue?

Code:
                      try:
                        ftr = rally.get('PortfolioItem',fetch=True,query='FormattedID = "F1234"')
                        f = ftr.next()
                      except:
                        logger.info('Error while fetching Feature for UserStory {}'.format(u.FormattedID))
                      try:
                        col = rally.addCollectionItems(f,milist)
                      except:
                        logger.error(traceback.format_exc())

Error:

Traceback (most recent call last):
  File "snow.py", line 173, in add_milestone
    col = rally.addCollectionItems(f,milist)
  File "C:\Users\xxxx\Anaconda3\lib\site-packages\pyral\restapi.py", line 1219, in addCollectionItems
    response = RallyRESTResponse(self.session, context, resource, response, "shell", 0)
  File "C:\Users\xxxx\Anaconda3\lib\site-packages\pyral\rallyresp.py", line 127, in __init__
    raise RallyResponseError(problem)
pyral.rallyresp.RallyResponseError: Response for request: PortfolioItem/402595004184/Milestones/add either was not JSON content or was an invalidly formed/incomplete JSON structure

**Comment by klehman-rally** [comment]
This has been fixed in the 1.5.0 release.
