### ISSUE TITLE
How can we override "User" name in "Revision History" in case we are using service account API key of Rally?

### ISSUE THREAD

**Issue by deepaklearner** [RallyTools/RallyRestToolkitForPython#171]
How can we override "User" name in "Revision History" in case we are using service account API key of Rally?

Details:
I am trying to connect Gitlab to Rally. So that any developer does a merge or commit any code. That will trigger a webhook. And that webhook, I am using to get "user, user story, task, hours, state etc details" and then parse them using python from the json.

Later, using this RestToolKit of python, I was even able to connect to Rally.

But one small issue I am facing is, with feature in Rally "Revision History". When I am trying to connect using Service API key, through python then as shown in below snapshot, the "User" field is coming as "System Account". I want to pass the user name who did commit in Gitlab. Is there any way to do this or any workaround.

![Rally_issue](https://user-images.githubusercontent.com/17330183/91624772-2edbff00-e970-11ea-8dbb-975420f50675.png)

**Comment by kent-pawar** [comment]
@deepaklearner Hi Deepak. Did you solve this? I guess the display name "System Account" can be updated by the Rally admin..?

**Comment by kent-pawar** [comment]
@deepaklearner Hi Deepak. Did you solve this?

**Comment by klehman-rally** [comment]
This capability to impersonate another user or perform operations as a proxy for another user and have the Rally system record an arbitrary user as the actor of record is not supported at this time in the Rally WSAPI.  This may change in the future and there have been discussions regarding this topic but there are no plans to support that at this time.
