### ISSUE TITLE
AttributeError: 'RallyRESTResponse' object has no attribute 'req_type'

### ISSUE THREAD

**Issue by Etraud123** [RallyTools/RallyRestToolkitForPython#37]
When i tried to get a defect:

rally = Rally(server, user, pwd)
#rally.enableLogging('mypyral.log')

query_criteria = 'ObjectID = "%s"' % args[0]
response = rally.get('Defect', query=query_criteria)
print response

Why i get this error? pyral version 1.1.0 Rally API 2.0

**Comment by klehman-rally** [comment]
fixed in 1.1.1
