### ISSUE TITLE
AttributeError: User instance has no attribute: 'UserProfile'

### ISSUE THREAD

**Issue by jay6413682** [RallyTools/RallyRestToolkitForPython#40]
How to reproduce:

import sys
from pyral import Rally, rallyWorkset
    
options = [opt for opt in sys.argv[1:] if opt.startswith('--')]
server, user, password, apikey, workspace, project = rallyWorkset(options)
print " ".join(['|%s|' % opt for opt in [server, user, password, apikey, workspace, project]])
rally = Rally(server, user, password, workspace=workspace, project=project)
users = rally.getAllUsers()

-------------------------------------------
Traceback:
...
  File "/Library/Python/2.7/site-packages/pyrallei/restapi.py", line 572, in getAllUsers
    if prof._ref == user.UserProfile._ref] 
  File "/Library/Python/2.7/site-packages/pyrallei/entity.py", line 159, in __getattr__
    raise AttributeError(description)
AttributeError: User instance has no attribute: 'UserProfile'

---------------------------------------------
pyral 1.1.0/python 2.7.6/Rally API 2.0

**Comment by michaelusner** [comment]
I've also encountered this issue.
My fix was to add the following to line 571:
`if hasattr(user, 'UserProfile') and` .....

**Comment by klehman-rally** [comment]
Incorporated user contributed code in 1.1.1

**Comment by evogirossdrew** [comment]
I'm still getting this in 1.1.1 when doing rally.getAllUsers()

Traceback (most recent call last):
  File "C:\Users\ross\python\integration_rally-trello\rallyPython.py", line 67, in <module>
    all_users = rally.getAllUsers()
  File "C:\Python27\lib\site-packages\pyral\restapi.py", line 575, in getAllUsers
    warning("%s" % (problem % (user.DisplayName, user.UserProfile)))
  File "C:\Python27\lib\site-packages\pyral\entity.py", line 172, in __getattr__
    raise AttributeError(description)
AttributeError: User instance has no attribute: 'UserProfile'
