### ISSUE TITLE
Exposing the search api

### ISSUE THREAD

**Issue by fruch** [RallyTools/RallyRestToolkitForPython#44]
I wanted to use the search:
slm/webservice/v2.x/search

could figure out how to do it correctly with pyral

anyone have any idea ?

**Comment by klehman-rally** [comment]
Snarfing from the Chrome Dev tools interface, a search request looks like the following:  https://rally1.rallydev.com/slm/webservice/v2.x/search?pagesize=25&start=1&fetch=true&includePermissions=true&compact=true&project=%2Fproject%2F123456789&projectScopeUp=false&projectScopeDown=true&keywords=wsapi%20documentation&searchScopeOid=987654321&searchScopeUp=false&searchScopeDown=true&searchScopeType=project&recycledItems=true&_slug=%2Fsearch

As it stands now that pyral doesn't expose a 'search' method on the pyral Rally instance that is used for coordinating the request/response interaction with Rally.
The current result by attempting to use the 'get' method results in an error emitting the following:pyral.entity.InvalidRallyTypeNameError: search .
However, it might not be a lot of effort to add 'Search' as a quasi-entity in pyral and provide a 'search' method in the pyral Rally instance to marshal the required elements of the query_string and have some reasonable set of option arguments for the search operation (scoping, inclusion/exclusion of recycle bin items, etc.).
I'll offer no timeframe, but this seems like a useful capability to add to pyral and I'll plan to include this in future work.

**Comment by fruch** [comment]
Yeah I assumed it quite simple, but I couldn't figure exactly how to add it myself.

Anyhow I was writing a command line frontend for rally for our daily use, (using click)
And search seemed like a very powerful tool for such frontend.

Thanks for the quick response

**Comment by klehman-rally** [comment]
Basic support for search added in 1.1.1.  There is now a search method available on a pyral.Rally instance.  It returns SearchObject instances (not instances of Artifact, Story, Defect, etc).
