### ISSUE TITLE
Pyral only allows for keying off the workspace by string name

### ISSUE THREAD

**Issue by kthayn** [RallyTools/RallyRestToolkitForPython#5]
Pyral will only allow you to set your workspace by string name.  It does not matter whether you do it when creating a new Rally connection or later with rally.setWorkspace.  Because Rally allows you to have multiple workspaces with the same name you would need to key off of the ref to make sure you are hitting the correct workspace.

**Comment by klehman-rally** [comment]
No plans to add this feature at this time, this is a corner case that would be best addressed by renaming the duplicate workspace name to a unique string.
