### ISSUE TITLE
KeyError: 'Results'

### ISSUE THREAD

**Issue by loliof** [RallyTools/RallyRestToolkitForPython#55]
Using v1.1.1

Making a simple script to print Defect names. The first defects prints fine, however the second receives an error. 

Traceback (most recent call last): 
    File "simple.py", line 21, in <module>
        print response
    File "C:\Python27\lib\site-packages\pyral\rallyresp.py", line 378, in __repr__
        (self.request_type, self.resultCount, self.content['Results'])
KeyError: 'Results'

Here's the code I'm using, not sure if you will need it. Let me know if you need my log as well.

import sys
from pyral import Rally, rallyWorkset, rallySettings

username = raw_input('Username: ')
pwd = raw_input('Password: ')

rally = Rally('rally1.rallydev.com', username, pwd)
rally.enableLogging('mypyral.log')

###This Defect works.###
response = rally.get('Defect', fetch=True, query='FormattedID = DE3179')
print response
for story in response:
	print story.Name

###This Defect does not.###
response = rally.get('Defect', fetch=True, query='FormattedID = DE3557')
print response
for story in response:
	print story.Name

**Comment by klehman-rally** [comment]
One thing that comes to mind here is whether your second Defect (DE3557) is in your default Workspace. As the pyral.Rally instance that you obtain doesn't specify a specific workspace/project, the operation is set to proceed using your default workspace for subsequent operations.  To be very precise you may want to specify the workspace and project in the the rally.get call.

**Comment by klehman-rally** [comment]
Unable to reproduce.
