### ISSUE TITLE
Api Key Proxy Issue

### ISSUE THREAD

**Issue by amcolosk** [RallyTools/RallyRestToolkitForPython#59]
I am trying to replace my old username/password Rally authentication with Rally API Keys. I'm using pyral 1.1.1 and requests 2.3.0 on a redhat server.

```
server, user, password, workspace, proj = rallySettings(options) rally = Rally(server, user, password)
```
to
```
rally = Rally(server='rally1.rallydev.com', apikey='SECRET_KEY')
```
When I made the change, I started getting errors like: ('Cannot connect to proxy.', gaierror(-5, 'No address associated with hostname')).

If I switch back to the old user/password route, it works just fine.

Here's how I am setting the proxy:
```
proxy = "http://internal.proxy.com:port"
os.environ['HTTPS_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTP_PROXY'] = proxy
```
Looking at the web commands being issued, I can see healthy behavior which looks like:

https://rally1.rallydev.com/slm/webservice/v2.0/User?fetch=true&query=(UserName%20%3D%20%22user%40company.com%22)&pagesize=100&start=1 120 <Response [200]>
https://rally1.rallydev.com/slm/webservice/v2.0/Subscription?fetch=true&pagesize=100&start=1 120 <Response [200]> https://rally1.rallydev.com/slm/webservice/v2.0/subscription/1904178192/Workspaces?fetch=true&query=(State = Open)&pagesize=200&start_index=1?pagesize=200&start=1 120 <Response [200]>
https://rally1.rallydev.com/slm/webservice/v2.0/Workspace/1904178204/Projects?fetch="ObjectID,Name,State"&pagesize=200&start_index=1?pagesize=200&start=1 120 <Response [200]>

With the API key turned on, I see:
https://rally1.rallydev.com/slm/webservice/v2.0/User?fetch=true&pagesize=100&start=1 120 <Response [200]>
https://rally1.rallydev.com/slm/webservice/v2.0/Subscription?fetch=true&pagesize=100&start=1 120 ('Cannot connect to proxy.', gaierror(-5, 'No address associated with hostname'))

So it succeeds behind a proxy for the first query, but not the second. 

I can connect using curl:
```
curl -x httpL//proxy.com:80 --header "zsessionid:_apiKey " -H "Content-Type: application/json" https://rally1.rallydev.com/slm/webservice/v2.0/hierarchicalrequirement?workspace=workspace/ 12352608129
```

**Comment by klehman-rally** [comment]
Unable to reproduce in my environment using squid (both non-authenticating and authenticating).  
Feel free to submit another issue if you are still having this problem and can provide any more information that would allow me to better match your operating environment so that I can reproduce the behavior you are seeing.
