### ISSUE TITLE
pyral.context.Pinger considered harmful

### ISSUE THREAD

**Issue by jordemort** [RallyTools/RallyRestToolkitForPython#62]
Before attempting to connect to Rally via HTTP, pyral uses the pyral.context.Pinger class to attempt to ping the server to see if it is reachable. This is problematic for several reasons:

  - It is implemented by calling out to an external "ping" binary, which may or may not be available
    - Some security-conscious administrators are prone to removing the setuid bit from the ping binary, rendering it useless to anyone but root
  - Instead of using the tmpfile module, it writes the output of this call to a file called ".ping-bucket" in the current working directory, which is problematic for a number of reasons
    - This presumes that the current working directory is writable, and fails badly if it isn't
    - If you're running multiple instances of a script that use pyral in parallel, they could end up stomping on each other
    - Predictable temporary file names are a favorite attack vector of malicious individuals
  - It assumes that the host it is running on is able to transmit and receive ICMP ping packets
    - Some admittedly-misguided administrators are prone to filtering all ICMP
    - A host being pingable or not pingable is not a particularly good predictor of being reachable or not reachable via HTTP

I was going to submit a pull request to update Pinger to use tmpfile instead of "./.ping-bucket" but upon further consideration I think it would be better for it to be removed entirely. All it does is introduce several more ways to fail, which may or may not actually have anything to do with the availability of the Rally API. If there are network issues that are preventing you from reaching the API, then the HTTP connection will fail, and you can report the error from that, instead of trying some arbitrary test first.

**Comment by patknight** [comment]
We need to access Rally from a secure, locked down, environment and our administrators won't allow ping out of the environment. So I'd like add support for removing Pinger.

**Comment by patknight** [comment]
Just opened pull request #64 with a tested fix that removes the ping and the Pinger class.

**Comment by visshal** [comment]
I created similar issue, that is duplicate.

**Comment by ericw13** [comment]
I have a pyral implementation deployed in a Docker container.  The base image does not include a ping binary and should not be needed.  I created a patch based off of patknight's change that is working well.  Would like to see this change made official.

**Comment by klehman-rally** [comment]
release of 1.2.0 starts the deprecation and removal sequence. In 1.2.0 there are env var and command line args as well as direct server_ping=false arg to Rally constructor that will allow bypass of pinging the Rally server.  Subsequent releases will eventually make server_ping=false the default and eventually the 2.0.0 release will remove the ping operation entirely.
