### ISSUE TITLE
Download Links on pypi.python.org are incorrect for pyral 1.1.1

### ISSUE THREAD

**Issue by neilvana** [RallyTools/RallyRestToolkitForPython#65]
Pyral is hosted on pypi as a tgz file, but additional links are made to the github export location from pypi.  However these links are incorrect.  See:

https://pypi.python.org/simple/pyral/

Look for the link entitled "1.1.1 download_url"  This link incorrectly points to:

https://github.com/RallyTools/RallyRestToolkitForPython/blob/master/dists/pyral-1.1.1.zip

Instead of correctly pointing to:

https://github.com/RallyTools/RallyRestToolkitForPython/raw/master/dists/pyral-1.1.1.zip

This causes problems for mirror servers that link to the zip file hosted on github (for example devpi).  

For example try running:
pip install -i https://devpi.net/root/pypi pyral==1.1.1

This produces an error that this isn't a zip file since the html that hosts the zip file is not the same as the zip file.  This problem also exists for other versions of pyral, but doesn't for all (for example 0.9.2 is correct)

**Comment by neilvana** [comment]
So, it looks like someone manually fixed this on pypi.python.org for 1.1.1, hopefully this will still get fixed in the master branch so future versions aren't broken too.

**Comment by klehman-rally** [comment]
This issue seems to have been addressed since v1.2.0.  V1.2.4 release is soon and I'll confirm that it works through that version also.
