### ISSUE TITLE
Rally pyral sdk error with a query with more than two terms. (Error parsing expression — expected “)” but saw “AND” instead.)

### ISSUE THREAD

**Issue by markwilliams970** [RallyTools/RallyRestToolkitForPython#7]
A valid query string defined by a tuple, fails any time a tuple is used with more than two terms.  Here is test code to repro (see http://stackoverflow.com/questions/14675004/rally-pyral-sdk-error-with-a-query-with-more-than-two-terms-error-parsing-expr )

import pyral

rally = pyral.Rally('rally1.rallydev.com', 'user@example.com', 'password')

user = rally.getUserInfo(name='User Name').pop(0)
wksp = rally.getWorkspace()
proj = rally.getProject()

print user.FirstName, user.LastName
print wksp.Name
print proj.Name

queryStrings = (
('State != "Closed"', 'Owner = ' + user.ref),
('State != "Fixed"', 'Owner = ' + user.ref),
('State != "Closed"', 'State != "Fixed"'),
('State != "Closed"', 'State != "Fixed"', 'Owner = ' + user.ref),
('State != Closed', 'State != Fixed', 'State != Submitted'),
('State != Fixed', 'ScheduleState != Tested'),
('State != Fixed', 'Owner = ' + user.ref, 'ScheduleState != Tested'),
)

for query in queryStrings:
    print "++++++++++++++++++++++++++++++++++++++++++"
    print "Query:",query
    defects = rally.get("Defect", True, query=query)
    print "Number of results:",defects.resultCount
    print "Errors:", defects.errors
    print
And here is the resulting output

User Name
A Workspace
Web Project
++++++++++++++++++++++++++++++++++++++++++
Query: ('State != "Closed"', u'Owner = user/1234567890')
QUERYJUNK: ((State != "Closed") AND (Owner = user/1234567890))
Number of results: 25
Errors: []

++++++++++++++++++++++++++++++++++++++++++
Query: ('State != "Fixed"', u'Owner = user/1234567890')
QUERYJUNK: ((State != "Fixed") AND (Owner = user/1234567890))
Number of results: 89
Errors: []

++++++++++++++++++++++++++++++++++++++++++
Query: ('State != "Closed"', 'State != "Fixed"')
QUERYJUNK: ((State != "Closed") AND (State != "Fixed"))
Number of results: 149
Errors: []

++++++++++++++++++++++++++++++++++++++++++
Query: ('State != "Closed"', 'State != "Fixed"', u'Owner = user/1234567890')
QUERYJUNK: ((State != "Closed") AND (State != "Fixed") AND (Owner = user/1234567890))
Number of results: 0
Errors: [u'Could not parse: Error parsing expression -- expected ")" but saw "AND"       instead.']

++++++++++++++++++++++++++++++++++++++++++
Query: ('State != Closed', 'State != Fixed', 'State != Submitted')
QUERYJUNK: ((State != Closed) AND (State != Fixed) AND (State != Submitted))
Number of results: 0
Errors: [u'Could not parse: Error parsing expression -- expected ")" but saw "AN

**Comment by rdkworld** [comment]
@klehman-rally  Look at your June 27 2014 comment, I was assuming this is fixed in 1.0.1. However, I tried today with current version and same issue exists...
