### ISSUE TITLE
Extraneous line in examples/getitem.py causes credentials error

### ISSUE THREAD

**Issue by herbdool** [RallyTools/RallyRestToolkitForPython#71]
In examples/getitem.py, the line "rally = Rally(server, user, password)" seems to be there in error. It overwrites the first assignment of the variable. I can only get the file to work if I remove it.

```
    if apikey:
        rally = Rally(server, apikey=apikey, workspace=workspace, project=project)
    else:
        rally = Rally(server, user=username, password=password, workspace=workspace, project=project)

    rally = Rally(server, user, password)      # specify the Rally server and credentials

**Comment by klehman-rally** [comment]
Fixed in 1.2.0.  I scanned through some of the other example scripts and think they are OK.  Please request a re-open or just open a new issue if you see this problem in any of the other example scripts.
