### ISSUE TITLE
KeyError: u'Subscription' while trying to obtain Rally object

### ISSUE THREAD

**Issue by Stabmeqt** [RallyTools/RallyRestToolkitForPython#75]
Hi.

Since today, pyral stopped working. I'm trying to obtain Rally object in a usual way:

`
options = ['--rallyServer=%s' % 'rally1.rallydev.com', '--workspace=%s' % currentUser.getWorkspace(), '--project=%s' % currentUser.getProject()]
    options.append('--rallyUser=%s' % 'currentUser.getUser()')
    options.append('--rallyPassword=%s' % currentUser.getRlPass())
               
    server, user, password, apikey, workspace, project = rallyWorkset(options)
            
    try:
        if apikey:
            Rally(server, apikey=apikey, workspace=workspace, project=project)
        else:
            Rally(server, user=user, password=password, workspace=workspace, project=project)                
    except Exception as e:
        print e
`

and I'm getting an exception:

`Traceback (most recent call last):  
  File "/venv/local/lib/python2.7/site-packages/pyral/restapi.py", line 228, in __init__
    self.contextHelper.check(self.server)
  File "/venv/local/lib/python2.7/site-packages/pyral/context.py", line 226, in check
    processSchemaInfo(self.getWorkspace(), schema_info)
  File "/venv/local/lib/python2.7/site-packages/pyral/entity.py", line 868, in processSchemaInfo
    item = SchemaItem(raw_item_info)
  File "/venv/local/lib/python2.7/site-packages/pyral/entity.py", line 645, in __init__
    self.Attributes.append(SchemaItemAttribute(attr))
  File "/venv/local/lib/python2.7/site-packages/pyral/entity.py", line 717, in __init__
    self.Subscription  =     attr_info[u'Subscription']
KeyError: u'Subscription'`

Reminder: yesterday all was working perfectly. Does that mean that Rally did some API changes?

**Comment by davejcameron** [comment]
@Stabmeqt I have a pull request with a fix #74

**Comment by Stabmeqt** [comment]
@davejcameron this issue got resolved by itself. I wrote a ticket to Rally support, and they respond that  they had already fixed it:

`Thank you for contacting CA Agile Central support regarding the error being received with the Pyral python toolkit. We have resolved this issue and it should now be connecting and functioning as expected. If you continue to experience issues, please let us know`

Looks like they had actually broke it :)
