### ISSUE TITLE
Updating Tag in rally

### ISSUE THREAD

**Issue by Amit232** [RallyTools/RallyRestToolkitForPython#78]
Hi,
I have been using pyral extensively.
If you query rally for a Test Case's "tags" using pyral's get() API and  appropriate query_criteria a list is returned.

My understanding is that this "Tags" list internally has elements which are dictionaries themselves and contain the attribute "Name" which represents the name of the tag.

Hence when you the following:
for testCase in response:
     print(testCase.Tags[0].Name) -> you get the appropriate tag name.

pyral's update() is used to update necessary fields.(it takes a dictionary as an argument)
It would be very helpful if you could provide a code snippet depicting how to update a "Tags" name using pyral's update API.

**Comment by klehman-rally** [comment]
The updtag.py script was added in 1.2.0 to illustrate how to update a Tag Name value.
