### ISSUE TITLE
Pyral: function addAttachment cannot add binary files like pictures

### ISSUE THREAD

**Issue by jfthuong** [RallyTools/RallyRestToolkitForPython#80]
The function `addAttachment` in restapi.py cannot correctly add picture files: the picture file is attached indeed but with a incorrect content (only 1 kB of data).

Such pictures are not valid data.

The issue come from the way the files are read

	with open(filename, 'r') as af:
		contents = base64.b64encode(af.read())

The file should be read as binary `open(filename, 'rb')`

**Comment by klehman-rally** [comment]
This issue addressed using your code modification in v1.2.0.
