### ISSUE TITLE
Reference to Feature.Parent.FormattedID throws error

### ISSUE THREAD

**Issue by ericw13** [RallyTools/RallyRestToolkitForPython#86]
Sample script:

>>> from pyral import Rally, rallyWorkset
>>> rallyServer = rallyWorkset([])[0]
>>> s=Rally(rallyServer, apikey='my-key-here', user=None, password=None)
>>> q='FormattedID = "F1467"'
>>> f="Name,Parent"
>>> data=s.get('Feature', query=q, fetch=f)
>>> print data.resultCount
1
>>> for x in data:
...    print x.Name, x.Parent.FormattedID
...
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/pyral/entity.py", line 140, in __getattr__
    item = response.content[rallyEntityTypeName]
KeyError: u'Businessepic'

>>> data=s.get('Feature', query=q, fetch=f)
>>> for x in data:
...    print x.Name, x.Parent.Name
...
General Enhancements Finance Operational

As this shows, I can reference Feature.Parent.Name no problem, but it doesn't like Feature.Parent.FormattedID.  

I've tried this starting with a UserStory as well, and get the same error on a reference to Story.Feature.Parent.FormattedID

**Comment by ericw13** [comment]
Observations:

Requesting fields f="FormattedID,Parent" allows me to reference Parent.FormattedID.  Requesting f="Name,Parent" does not allow me to reference Parent.FormattedID.  f=True also bombs on reference to Parent.FormattedID.

As a workaround, I'm just going to add FormattedID to the fetch string, even if I already have the current item's value.

**Comment by klehman-rally** [comment]
If you want to reference a field in a parent/other relationship entity that is an attribute within the entity specified, you should specify that field name in the fetch list (fetch=True doesn't result in being able to reference parent/child fields, only the fields in the specific entity asked for).
