### ISSUE TITLE
getAllowedValues() problems

### ISSUE THREAD

**Issue by calwas** [RallyTools/RallyRestToolkitForPython#89]
I'm running pyral 1.2.0 on Python 2.7.10 and requests 2.8.1.
#1 The getAllowedValues() method throws an exception on the return statement when it is passed entityName: 'UserStory' and attributeName: 'Milestones'. The exception message is "AttributeError: 'str' object has no attribute 'StringValue'.
#2 Ignoring the exception, the method still would not have returned the correct list of allowed values. The method would have incorrectly returned an empty list [] even though allowed values have been defined for it. In fact, an empty list is returned not only for the Milestones attribute, but for any attribute whose Attributes.AllowedValues field contains a reference, as in https://.../attributedefinition/-nnnnn/AllowedValues. They all return an empty list even if allowed values have been defined for the attribute.

**Comment by klehman-rally** [comment]
The release of pyral 1.2.1 addressed some of these issues.  At some point in the past, only attributes with "real" allowed values (a finite set of more than 1 value) had allowedValues refs associated.  Within the last year, more attributes now have an allowed value ref but the set sometimes now consists of a single True value.  pyral 1.2.1 will now return a list of [True] in those instances for instance when attempting to retrieve allowed values for attributes like Milestones (and numerous others).  There are very few attributes (those with a type of STATE or RATING and comparatively rarely STRING) that have "useful" allowed values.
