### ISSUE TITLE
The six package is missing when upgrading to pyral 1.2.0 via pip 

### ISSUE THREAD

**Issue by calwas** [RallyTools/RallyRestToolkitForPython#90]
I'm running pyral 1.2.0 on Python 2.7.10 and requests 2.8.1.

I upgraded pyral 1.1.1 to 1.2.0 by running 'python -m pip install --upgrade pyral'. When I run my application, pyral crashes when it attempts to 'import six'.

Manually installing the six package by running 'pip install six' eliminates the crash.

**Comment by mattguymad** [comment]
Yep. Same problem. Pyral doesn't seem to install this a a pre-requisite.

**Comment by ClockerZadq** [comment]
Same

**Comment by klehman-rally** [comment]
This should be resolved in 1.2.1 with the addition explicit requirements in the setup.py and PKG-INFO file.  Re-open if this doesn't clear up the issue.
