### ISSUE TITLE
Cannot show details of user story if parent is a saga feature.

### ISSUE THREAD

**Issue by heoga** [RallyTools/RallyRestToolkitForPython#93]
I have a user story whose parent is a Saga Feature.  When I attempt to use details() on this I trigger the following traceback:
```
Traceback (most recent call last):
  File "UserStoryQuery.py", line 18, in <module>
    print(story.details())
  File "C:\Python35\lib\site-packages\pyral\entity.py", line 383, in details
    anv = "%s (OID  %s  FomattedID  %s)" % (anv, value.oid, value.FormattedID)
  File "C:\Python35\lib\site-packages\pyral\entity.py", line 147, in __getattr__
    item = response.content[rallyEntityTypeName]
KeyError: 'Sagafeature'
```

It looks like some parsing is being done of the lines in this area which is forcing PortfolioItem_SagaFeature to Sagafeature.  If I add a simple `.replace('Sagafeature', SagaFeature')` to line 114 like so:
`rallyEntityTypeName = entity_path.split('/')[-1].capitalize().replace('Sagafeature','SagaFeature')`

This seems to restore operation.  I'm sure there's a more elegant solution though.

**Comment by klehman-rally** [comment]
This should be fixed in 1.2.2 with [PR #63] (https://github.com/RallyTools/RallyRestToolkitForPython/pull/63) provided by yobnoj.
