### ISSUE TITLE
pyral v1.2.1 getAllowedValues() is useless

### ISSUE THREAD

**Issue by calwas** [RallyTools/RallyRestToolkitForPython#96]
The pyral v1.2.0 version of getAllowedValues() had issues described in Issue #89. Specifically, it threw an exception and would incorrectly return an empty list.

Version 1.2.1 returns a list with the single value of True. I fail to see how this return value is useful. Is it telling me that there are allowed values? I already knew that. I'm calling the method to retrieve them.

There are at least two valid reasons for retrieving the allowed values for a field. (1) Validate user input and (2) display the list of allowed values for user selection. The Rally web UI itself performs operation (2).

The ability to retrieve a field's allowed values is a standard capability that the pyral library needs to support.

**Comment by calwas** [comment]
In case anyone needs a workaround for the getAllowedValues() method, here is my solution.

For custom fields, use pyral v1.1.1 and include the "c_" prefix in the field's name.
For builtin fields, here is a method that specifically retrieves the allowed values of the Milestones field. For other builtin fields, use this method as a beginning template and update accordingly. The method accepts an argument of a Rally object and returns a list of allowed values. Tested with pyral 1.2.0.

def getAllowedMilestonesValues(rally):

    # Get the current Rally context and project reference
    context = rally.contextHelper.currentContext()
    projectRef = rally.contextHelper.currentProjectRef()

    # Construct the url
    resource = ('%s/Milestone?start=1&pagesize=200&fetch=Name&includePermissions=true&compact=true&project=%s'
               '&projectScopeUp=false&projectScopeDown=true' % (context.service_url, projectRef))

    # Call Rally
    response = None
    try:
        response = rally.session.get(resource, timeout=120)
    except Exception as ex:
        print 'Internal Exception: Could not retrieve allowed Milestones values. Status code: %s' % response.status_code
        return None

    if response.status_code != 200:     # HTTP Success code
        print 'Internal Error: Could not retrieve allowed Milestones values. Status code: %s' % response.status_code
        return None

    # Parse the Json response text into a Python data structure
    content = json.loads(response.content)

    # Construct list of Milestone Name strings
    allowedValues = []
    for milestone in content['QueryResult']['Results']:
        allowedValues.append(milestone['Name'])
    return allowedValues

**Comment by klehman-rally** [comment]
pyral does support obtaining all Milestone values in a workspace.  Milestone is a "subclass" of WorkspaceDomainObject and as such is more like a Tag or a Release entity than fields customarily thought of as a field with allowed values like Severity or Priority.  The simplest way to retrieve all the Milestone values is with a rally.get('Milestone', fetch="Name") much like your code example but without resorting to reaching inside the pyral implementation for context and session and looking for specific implementation codes and dict keys.  I've suppled a get_milestones.py script in the examples directory with the release of 1.2.2.   TLDR, In the early part of 2016, the WSAPI expanded the set of entity fields that provided an allowedValues endpoint.  Many of these fields whose type is STRING (not STATE or RATING) end up returning a boolean true value, which I will agree seems strange and discordant compared with the STATE and RATING type fields.  But, that's what is provided at this time.  For Artifacts, there appear to be only a very few STRING fields that provide intuitively sensical allowedValues results: for Defect (TestCaseStatus, TaskStatus, Package), for Story (TestCaseStatus, DefectStatus, TaskStatus, Package), for Task (State), for TestCase (DefectStatus, LastVerdict, Package, Type, Method).  Hope this helps.
