### ISSUE TITLE
Rally.get(pagesize=) defaults to 100, not 200

### ISSUE THREAD

**Issue by calwas** [RallyTools/RallyRestToolkitForPython#97]
pyral versions 1.1.1, 1.2.0, 1.2.1: The pyral documentation for the Rally.get() method states that the default pagesize argument is 200. In fact, the default is 100.

**Comment by klehman-rally** [comment]
Fixed in 1.2.2.  MAX_PAGESIZE value of 200 is used in all places.  Any mention/use of PAGESIZE has been expunged.
