### ISSUE TITLE
getAllowedValues() does not return allowed values for custom fields

### ISSUE THREAD

**Issue by calwas** [RallyTools/RallyRestToolkitForPython#99]
The getAllowedValues() method in pyral version 1.1.0 and 1.1.1 successfully retrieved the allowed values of custom fields (provided the field name included the 'c_' prefix). For versions 1.2.x, the method either throws an exception or returns a useless list containing the single value of True. The method used to work as documented and expected. Also, the Rally web interface is able to retrieve the allowed values of custom fields. The 1.2.x pyral implementations are a regression.

Is there a workaround for getting the allowed values of custom fields? The Milestone workaround provided in the 1.2.2 get_milestones.py example file is very useful, but does not work for custom fields. Similarly, the allowedValues.py example only works for certain field types, such as STRING. My custom field is processed by Rally as a collection. If the getAllowedValues() method is not going to be fixed, then a workaround would be appreciated.

**Comment by calwas** [comment]
I've done some sleuthing in the v1.2.2 getAllowedValues() method. It appears that the method does indeed retrieve the allowed values for a custom field, but the method short-circuits and never returns them.

If the three statements following the call to attribute.resolveAllowedValues() are removed (i.e., the if and the two return statements), then the allowed values for custom fields are returned by the method's final return statement.

The method still fails when passed a "built-in" field like Milestones (an empty list is returned), but there is a workaround for that situation which is demonstrated in the get_milestones.py example code.

It seems better to have a getAllowedValues() method that is at least partially functional and can be combined with workarounds, such as for Milestones, than the current 1.2.2 version method which is completely dysfunctional.

**Comment by calwas** [comment]
I developed my own workaround to retrieve the allowed values of a custom field. My implementation is specific to a hard-coded fieldname called c_Product, but the code can be easily generalized if needed. The method accepts a reference to a Rally object.

~~~~
def getAllowedProductValues(rally):

    # Get the list of attributes/fields available for a User Story AKA HierarchicalRequirement
    schemaItem = rally.contextHelper.getSchemaItem('HierarchicalRequirement')
    if not schemaItem:
        print 'Internal Error: Could not retrieve a list of User Story fields.'
        return None

    # Find our attribute in the schema
    for attrib in schemaItem.Attributes:
        if attrib.ElementName == 'c_Product':
            # Retrieve the attribute's collection of allowed values
            allowedValues = rally.getCollection(attrib.AllowedValues)
            if allowedValues.errors:
                print 'Internal Error: Could not retrieve available Products, error code: %d.\n' % allowedValues.status_code
                return None
            if allowedValues.resultCount == 0:
                # This should never happen
                print 'Internal Error: No Rally products found.'
                return None

            #Return a list of allowed values in lowercase
            return [allowedValue.StringValue.lower() for allowedValue in allowedValues]

    return None
~~~~

**Comment by klehman-rally** [comment]
The 1.2.3 has a modified getAllowedValues method that will treat a custom field in the manner as a standard field.  The getAllowedValues method takes two parameters, an entity name (like 'Defect' or 'Story'  / 'HierarchicalRequirement' or 'TestCase', etc. ) and an attribute name.  When specifying a custom field you do not need to prefix the name with 'c_', the method will do that as part of the processing.

**Comment by calwas** [comment]
Just tested this with 1.2.3 and 1.2.4. Both versions still return a list with the single value of True. This is no change from 1.2.2. I am passing 'HierarchicalRequirement' and a custom field name, such as 'Product' (or c_Product).

Also, the getAllowedValue() still does not work with standard fields, so the get_milestones.py workaround is still needed in 1.2.3 and 1.2.4.

Will open a new issue.
